required = [
	"github.com/GoASTScanner/gas/cmd/gas",
	"github.com/gobuffalo/pop/soda",
	"github.com/golang/lint/golint",
	"github.com/go-swagger/go-swagger/cmd/swagger",
	"github.com/codegangsta/gin",
	"github.com/segmentio/chamber",
	"github.com/docker/go-units"
	]

[[constraint]]
  name = "github.com/go-swagger/go-swagger"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/GoASTScanner/gas"
