required = [
	"github.com/securego/gosec/cmd/gosec",
	"github.com/gobuffalo/pop/soda",
  "golang.org/x/lint/golint",
	"github.com/go-swagger/go-swagger/cmd/swagger",
	"github.com/codegangsta/gin",
	"github.com/segmentio/chamber",
	"github.com/docker/go-units"
	]

[[constraint]]
  name = "github.com/go-swagger/go-swagger"
  branch = "master"

[[constraint]]
  name = "github.com/securego/gosec"
  branch = "master"

 [[constraint]]
  name = "github.com/trussworks/pdfcpu"
  branch = "afero"

[[constraint]]
  branch = "master"
  name = "go.mozilla.org/pkcs7"

[[constraint]]
  name = "github.com/99designs/aws-vault"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "golang.org/x/lint"
