name: Integration Testing Syncing

on:
  pull_request:
    branches: main
    types: closed
jobs:
  merge-main-to-int-testing:
    if: github.event.pull_request.merged == true
    timeout-minutes: 2
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set Git config
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"    
    - name: Merge main to integrationTesting-Dummy
      run: |
          git fetch --unshallow
          git checkout integrationTesting-Dummy
          git pull
          git merge --no-ff master -m "Auto-merge main to integrationTesting-Dummy"
          git push
